.PHONY: free
free:
	flutter pub pub run build_runner build --delete-conflicting-outputs

.PHONY: icon
icon:
	flutter pub pub run flutter_launcher_icons:main

.PHONY: splash
splash:
	flutter pub pub run flutter_native_splash:create